apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: containerproxy-build
spec:
  volumes:
    - name: dockersock  
      hostPath:
        path: /var/run/docker.sock        
  containers:
   - name: containerproxy-build
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/containerproxy-build 
     command:
     - cat
     tty: true
     volumeMounts:
      - mountPath: /var/run/docker.sock
        name: dockersock
