apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: containerproxy-build
spec:
  volumes:
    - name: maven-repo  
      hostPath:
        path: ~/.m2        
  containers:
   - name: containerproxy-build
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/containerproxy-build
     securityContext:
      privileged: true  
     command: ["sh"]
     args: ["/usr/src/app/docker-entrypoint.sh"]
     tty: true
     volumeMounts:
      - mountPath: ~/.m2
        name: maven-repo
